import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { POST } from '../../../../src/routes/projects/stripe-toddler-admin/api/inventory/upload/+server.js';
import * as requireUser from '$lib/server/require-user.js';

vi.mock('$lib/server/require-user.js', () => ({
	requireUser: vi.fn()
}));

// CI injects real admin API keys via Doppler, which would shadow the test
// values set below and make the header assertions non-deterministic (and
// potentially leak a real key prefix in failure output). Sandbox every key
// the proxy reads and restore the originals after each test.
/* eslint-disable security/detect-object-injection -- env sandbox deliberately uses dynamic keys */
const ADMIN_ENV_KEYS = ['TODDLER_ADMIN_API_KEY', 'ADMIN_API_KEY', 'STRIPE_TODDLER_ADMIN_API_KEY'];

const originalAdminEnv = new Map();

beforeEach(() => {
	originalAdminEnv.clear();
	for (const key of ADMIN_ENV_KEYS) {
		originalAdminEnv.set(key, process.env[key]);
		delete process.env[key];
	}
});

afterEach(() => {
	for (const key of ADMIN_ENV_KEYS) {
		if (originalAdminEnv.get(key) === undefined) {
			delete process.env[key];
		} else {
			process.env[key] = originalAdminEnv.get(key);
		}
	}
});

function makeFormData(barcode = 'TOY-001', image = 'fake-image-bytes') {
	const formData = new FormData();
	formData.append('barcode', barcode);
	formData.append('image', new Blob([image], { type: 'image/jpeg' }), 'toy.jpg');
	return formData;
}

function makeEvent({ fetchImpl, body }) {
	return {
		request: new Request('http://localhost/api/inventory/upload', {
			method: 'POST',
			body
		}),
		fetch: fetchImpl || vi.fn(),
		platform: { env: {} }
	};
}

describe('/projects/stripe-toddler-admin/api/inventory/upload/+server.js POST', () => {
	it('returns the not-authorised response when the user is not authenticated', async () => {
		const notAuthorised = new Response(null, { status: 401 });
		requireUser.requireUser.mockResolvedValue(notAuthorised);

		const event = makeEvent({ body: makeFormData() });
		const res = await POST(event);

		expect(res).toBe(notAuthorised);
		expect(event.fetch).not.toHaveBeenCalled();
	});

	it('proxies the multipart upload to the worker with the admin API key header', async () => {
		requireUser.requireUser.mockResolvedValue({ user: { id: 1 } });
		process.env.TODDLER_ADMIN_API_KEY = 'upload-admin-key-456';

		const uploadResponse = {
			image_url: 'https://stripe-toddler-images.example.r2.dev/images/TOY-001.jpg',
			barcode: 'TOY-001'
		};
		const fetchImpl = vi.fn().mockResolvedValue({
			ok: true,
			json: async () => uploadResponse
		});

		const event = makeEvent({ fetchImpl, body: makeFormData() });
		const res = await POST(event);

		expect(res.status).toBe(200);
		expect(await res.json()).toEqual(uploadResponse);

		const [url, init] = fetchImpl.mock.calls[0];
		expect(url).toBe('https://stripe-toddler.nick-brett1.workers.dev/api/admin/inventory/upload');
		expect(init.method).toBe('POST');
		expect(init.headers['X-Admin-API-Key']).toBe('upload-admin-key-456');
		expect(init.body).toBeInstanceOf(FormData);
		// The multipart boundary must be generated by the runtime, so the proxy
		// must not pin a Content-Type header that would break multipart encoding.
		expect(init.headers['Content-Type']).toBeUndefined();
	});

	it('returns 400 when barcode or image is missing', async () => {
		requireUser.requireUser.mockResolvedValue({ user: { id: 1 } });

		const event = makeEvent({ body: makeFormData('', '') });
		const res = await POST(event);

		expect(res.status).toBe(400);
		expect(event.fetch).not.toHaveBeenCalled();
	});

	it('relays the worker HTTP status when the worker responds with an error', async () => {
		requireUser.requireUser.mockResolvedValue({ user: { id: 1 } });
		const fetchImpl = vi.fn().mockResolvedValue({
			ok: false,
			status: 413,
			statusText: 'Payload Too Large'
		});

		const event = makeEvent({ fetchImpl, body: makeFormData() });
		const res = await POST(event);

		expect(res.status).toBe(413);
		const body = await res.json();
		expect(body.error).toBe('Worker returned HTTP 413');
	});

	it('returns 500 with the error message when the worker fetch fails', async () => {
		requireUser.requireUser.mockResolvedValue({ user: { id: 1 } });
		const fetchImpl = vi.fn().mockRejectedValue(new Error('Load failed'));

		const event = makeEvent({ fetchImpl, body: makeFormData() });
		const res = await POST(event);

		expect(res.status).toBe(500);
		const body = await res.json();
		expect(body.error).toBe('Load failed');
	});
});
