# Modified CircleCI configuration for dual wrangler approach
# This replaces the secret syncing step in the deploy job

# In the deploy job, replace the secret syncing step with:
      - run:
          name: Sync Doppler secrets to Cloudflare (production) - using wrangler 4.42.2
          command: |
            cd webapp
            echo "Attempting to sync secrets to Cloudflare production environment using wrangler 4.42.2..."
            if ./scripts/sync-secrets-with-wrangler-4.42.2.sh; then
              echo "✅ Secrets successfully synced to Cloudflare production"
            else
              echo "❌ Error: Failed to sync secrets to Cloudflare production. This is critical for production deployments."
              exit 1
            fi

# The rest of the configuration remains the same
