# Generated by Django 4.0.4 on 2022-06-16 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('event', models.IntegerField(choices=[(0, 'Login'), (1, 'Change Page')])),
                ('args', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='InfoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('lastPage', models.IntegerField(choices=[(0, 'Bills'), (1, 'Info')])),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.infocategory')),
            ],
        ),
        migrations.CreateModel(
            name='Charges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.IntegerField(choices=[(0, 'Fat Chase'), (1, 'Freedom'), (2, 'Hyatt'), (3, 'Amazon')])),
                ('npayment', models.FloatField(null=True)),
                ('tpayment', models.FloatField(null=True)),
                ('status', models.IntegerField(choices=[(0, 'Unallocated'), (1, 'Allocated')], default=0)),
                ('bill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.bills')),
            ],
        ),
    ]
