# Generated by Django 4.0.4 on 2022-06-17 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_text_info_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='info',
            new_name='text',
        ),
    ]
