# Generated by Django 4.0.4 on 2022-06-17 13:55

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('main', '0004_activity_time_bills_date_bills_namount_bills_tamount_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Activity',
            new_name='Action',
        ),
        migrations.RenameModel(
            old_name='Bills',
            new_name='Bill',
        ),
        migrations.RenameModel(
            old_name='Charges',
            new_name='Charge',
        ),
        migrations.RenameModel(
            old_name='Settings',
            new_name='Setting',
        ),
    ]
