# Generated by Django 4.0.4 on 2022-06-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_activity_action_rename_bills_bill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infocategory',
            name='image',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='infocategory',
            name='name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
