# Generated by Django 4.0.4 on 2022-06-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_infocategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infocategory',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
