# Generated by Django 4.0.4 on 2022-06-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_infocategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infocategory',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
