# Generated by Django 4.0.4 on 2022-06-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_infocategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='text',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='infocategory',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
