# Generated by Django 4.0.4 on 2022-06-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_info_text_alter_infocategory_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='text',
        ),
        migrations.AddField(
            model_name='info',
            name='field',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='info',
            name='value',
            field=models.CharField(default='', max_length=50),
        ),
    ]
