# Generated by Django 4.0.4 on 2022-06-19 02:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_info_text_info_field_info_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='charge',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
