name = "amazon-orders-worker"
main = "src/worker-basic.js"
compatibility_date = "2024-01-01"

# Python worker configuration
[build]
command = ""

# Bindings
[[kv_namespaces]]
binding = "AMAZON_CACHE"
id = "712063976dba4c4aab8ac8910b735afa"
preview_id = "712063976dba4c4aab8ac8910b735afa"

[[d1_databases]]
binding = "ORDERS_DB"
database_name = "amazon-orders-db"
database_id = "0989d97b-ab68-4bf5-abed-78d943144c32"

# Environment variables (add your Amazon credentials here)
[vars]
# AMAZON_EMAIL = "your-amazon-email@example.com"
# AMAZON_PASSWORD = "your-amazon-password"
# You can also use secrets for sensitive data:
# wrangler secret put AMAZON_EMAIL
# wrangler secret put AMAZON_PASSWORD

# Development settings
[dev]
port = 8787
local_protocol = "http"

# Route configuration (optional - configure as needed)
# routes = [
#   { pattern = "amazon-orders.example.com/*", zone_name = "example.com" }
# ]
