name = "worker"
main = "src/index.js"
compatibility_date = "2022-10-05"
send_metrics = true
routes = [{pattern = "*bemstudios.uk/*", zone_name = "bemstudios.uk"}]
kv_namespaces = [
  { binding = "KV", id = "b96b6adb766f49b7bd70416cee641fc8", preview_id = "8c54a1e41d5147fbade0e7eca10edebc" },
]

# The necessary secrets are:
# - GOOGLE_CLIENT_SECRET
# Run `wrangler secret put <NAME>` for each of these