-- Project Generation Tool Database Schema
--
-- NOTE: This file is no longer used. Genproj now uses KV storage instead of D1 database.
--
-- The genproj feature originally used D1 database for:
-- - Authentication states (GitHub, CircleCI, Doppler, SonarCloud tokens)
-- - Project configurations
-- - Generated artifacts
-- - External service integrations
--
-- As of the KV refactor, all authentication state is now stored in KV (similar to Google auth),
-- and there is no need for persistent storage of project configurations or artifacts since
-- genproj is a "generate once and done" tool.
--
-- If you need to restore D1 support in the future, this schema can serve as a reference,
-- but the current implementation uses KV exclusively.

-- Authentication states (now stored in KV)
-- KV key: genproj_auth_{userId}
-- KV value: JSON with { google: {...}, github: {...}, circleci: {...}, doppler: {...}, sonarcloud: {...} }
-- KV expiration: Based on token expiration (default 1 hour)
