<script>
	import Milestone from '$lib/components/Milestone.svelte';
	import TwoSigma from '$lib/icons/TwoSigma.svelte';
	import Velma from '$lib/icons/Velma.svelte';
	import Messenger from '$lib/icons/Messenger.svelte';
	import CollaborativeGain from '$lib/icons/CollaborativeGain.svelte';
	import Bloomberg from '$lib/icons/Bloomberg.svelte';
	import LibraryHouse from '$lib/icons/LibraryHouse.svelte';

	const work = [
		{
			from: 'Sept 2025',
			to: 'Current',
			title: 'Head of Fast Forecasting Engineering',
			workplace: 'Trading Engineering @ Two Sigma',
			body: [
				'Responsible for a team of Trading Engineers and Quantitative Software Engineers that partner with multiple Two Sigma quant teams to produce short-horizon forecasts and features.'
			],
			logo: { Icon: TwoSigma, tooltip: 'Two Sigma', link: 'https://www.twosigma.com' }
		},
		{
			from: 'Feb 2025',
			to: 'Sept 2025',
			title: 'Data Engineering Strategic Engagement',
			workplace: 'Data Engineering @ Two Sigma',
			body: [
				"As a senior individual contributor I worked across the Two Sigma Data Engineering department to define and drive the strategic direction for an important external partnership. This work included a multi-year forward evaluation of the Data Engineering departments' technical capabilities and needs, with a mapping to the capabilities of the partner and a plan for how the partnership could succeed."
			],
			logo: { Icon: TwoSigma, tooltip: 'Two Sigma', link: 'https://www.twosigma.com' }
		},
		{
			from: 'Dec 2023',
			to: 'Feb 2025',
			title: 'Head of Data Platform & Differentiated Data Engineering',
			workplace: 'Data Engineering @ Two Sigma',
			body: [
				'Expanded scope to lead a second separate cross-functional team "Differentiated Data Engineering" of Data Engineers, Data Scientists and Program Managers.',
				"The team built and leveraged LLM technology to create differentiated proprietary datasets. Responsibilities encompassed three efforts; building tools that leverage LLM technology that can be used to deliver new sources of alpha, establishing systems and processes that allow the scalable validation and tuning of LLM's with human input, and building datasets with the team's LLM tools that themselves deliver alpha."
			],
			logo: { Icon: TwoSigma, tooltip: 'Two Sigma', link: 'https://www.twosigma.com' }
		},
		{
			from: 'Jan 2023',
			to: 'Dec 2023',
			title: 'Head of Data Platform',
			workplace: 'Data Engineering @ Two Sigma',
			body: [
				"Led a team of Data Engineers responsible for Two Sigma's Data Platform, a suite of tools and services that enable Alpha Modelers and other internal customers to discover, share and seamlessly use Two Sigma's vast catalog of vendor supplied, proprietary and derived datasets. Key products include a 'Feature Catalog', that organizes, indexes and permissions economically valuable time-series data (features), and a data lineage system for tracing all data flows across Two Sigma.",
				'Key achievements included establishing a process and mechanism to provide data lineage insights that delivered use-cases around risk management, support cost reduction and model attribution in a way that did not disrupt modeler workflow or require a rebuild of the existing architecture. Also developing systems to allow data upgrades to occur seamlessly, with alpha models migrated to new data sets with no disruption and minimal effort.'
			],
			logo: { Icon: TwoSigma, tooltip: 'Two Sigma', link: 'https://www.twosigma.com' }
		},
		{
			from: 'Oct 2020',
			to: 'Nov 2024',
			title: 'Advisor',
			workplace: 'Velma',
			body: [
				'Velma was a VC-backed early stage company using AI to make the process of planning and running large software projects more transparent, efficient and agile. Advised the CEO and executive team on company strategy, fundraising, market positioning and as a general sounding board for hard problems.'
			],
			logo: { Icon: Velma, tooltip: 'Velma', link: 'https://www.heyvelma.com' }
		},
		{
			from: 'Nov 2020',
			to: 'Dec 2022',
			title: 'Senior Engineering Manager',
			workplace: 'Messenger @ Meta',
			body: [
				'Responsible for multiple teams building the technology platform for the data generated by Messenger’s billions of users that processes and stores actionable data to be used by dozens of Meta’s teams for insight into customer usage and market trends. A key focus was ensuring that data was handled in a fundamentally private way by building a closed form data lineage system that allowed the company to make strong guarantees about data usage to comply with regulations around the world (e.g. EU Privacy Directive) and build greater user trust.'
			],
			logo: {
				Icon: Messenger,
				tooltip: 'Meta Messenger',
				link: 'https://www.messenger.com/'
			}
		},
		{
			from: 'Jan 2020',
			to: 'Jan 2021',
			title: 'Executive Council Member',
			workplace: 'Collaborative Gain',
			body: [
				"Participated in bi-weekly 1 hour meetings of 'councils' of like minded executives. Provided and received coaching on a range of challenges, from helping others scale their business, deal with role changes and identify opportunities for professional growth."
			],
			logo: {
				Icon: CollaborativeGain,
				tooltip: 'Collaborative Gain',
				link: 'https://collaborativegain.com//'
			}
		},
		{
			from: 'May 2019',
			to: 'Oct 2020',
			title: 'Head of Client Service for Data Contributions',
			workplace: 'Bloomberg LP',
			body: [
				'Led an 80+ global team of product managers, data engineers and customer success managers that grew the marketplace for Bloomberg’s 4000+ data partners. Improving data usage and reducing Bloomberg customer churn by enabling partners to spend less time enabling their customers for data (from weeks to <5 days per request), while also improving speed of historical data updates from multi-days to <24 hours.'
			],
			logo: {
				Icon: Bloomberg,
				tooltip: 'Bloomberg LP',
				link: 'https://www.bloomberg.com/'
			}
		},
		{
			from: 'Jan 2018',
			to: 'Apr 2019',
			title: 'Head of Product for Data Contributions',
			workplace: 'Bloomberg LP',
			body: [
				'With a team of 6 product managers and 2 data engineers grew the business by reducing the time to on-board new contributed content from months to weeks, removed interruptions in data service due to customer firm mergers, and reduced data processing errors from 3% of content to <0.1%. Launched a new Alternative Data business by reducing on-board time for vendors from weeks to days by developing a new data pipeline system on a Python micro-services no-SQL architecture.'
			],
			logo: {
				Icon: Bloomberg,
				tooltip: 'Bloomberg LP',
				link: 'https://www.bloomberg.com/'
			}
		},
		{
			from: 'Nov 2016',
			to: 'Jan 2018',
			title: 'New Engineering Initiative: Rapid Market Data Onboarding',
			workplace: 'Bloomberg LP',
			body: [
				'Worked as a senior IC on an exciting new initiative to reduce the time to onboard and normalize new market data feeds that historically relied on C++ programmers and bespoke transformation logic. Personally designed and built a functional prototype for a suite of Node.js / React tools that allowed data analysts with only limited Python expertise to define transformation rules in a WYSIWYG environment for market data. These rules were then used to both generate code directly for handling market data, but also to drive test plans and high quality specification documents for C++ engineers to develop modules more efficiently that could not be cost effectively generated.',
				'This prototype led to a seven figure funding plan for a team of Engineers to build out a fully fledged product offering that as of Oct 2020 had been deployed across ~6 exchanges with reductions in both time to market and maintenance costs of their respective market data feeds.'
			],
			logo: {
				Icon: Bloomberg,
				tooltip: 'Bloomberg LP',
				link: 'https://www.bloomberg.com/'
			}
		},
		{
			from: 'Nov 2014',
			to: 'Nov 2016',
			title: 'Engineering Manager',
			workplace: 'Equity Sales Applications @ Bloomberg LP',
			body: [
				'Engineering manager for 5 teams (30 reports) in London and New York building a new product (DASH), for equity salespeople. Developed in C++ and JavaScript, the software offers a matching algorithm to combine data and find opportunities to save users time; achieved over 3000+ daily active users over 18 months. Secured funding for 10 developers after pitching to Bloomberg LP CEO a new business intelligence platform for sales managers based around a personally coded C++ prototype.'
			],
			logo: {
				Icon: Bloomberg,
				tooltip: 'Bloomberg LP',
				link: 'https://www.bloomberg.com/'
			}
		},
		{
			from: 'Apr 2011',
			to: 'Nov 2014',
			title: 'Engineering Manager',
			workplace: 'Market Analytics @ Bloomberg LP',
			body: [
				'Manager of 4 varied teams in 3 countries with 22 reports that built growing products, from batch-based trade analysis reporting software (BTCA) that achieved >3 million USD revenue growth, to realtime VWAP price calculation engines in C++ that processed thousands of market events per second.'
			],
			logo: {
				Icon: Bloomberg,
				tooltip: 'Bloomberg LP',
				link: 'https://www.bloomberg.com/'
			}
		},
		{
			from: 'May 2008',
			to: 'Apr 2011',
			title: 'Engineering Team Leader',
			workplace: 'Realtime Market Analytics @ Bloomberg LP',
			body: [
				'Grew usage from 3,000 to 40,000 active users over 2 years by leading a team of 8 developers building a suite of applications for realtime market analysis.'
			],
			logo: {
				Icon: Bloomberg,
				tooltip: 'Bloomberg LP',
				link: 'https://www.bloomberg.com/'
			}
		},
		{
			from: 'Apr 2006',
			to: 'Mar 2008',
			title: 'Software Engineer',
			workplace: 'Bloomberg LP',
			body: [
				'Developed a market data alert system using C/C++ in a distributed UNIX environment that delivered 3000 to 4000 alerts a second to users with 24/7 availability.'
			],
			logo: {
				Icon: Bloomberg,
				tooltip: 'Bloomberg LP',
				link: 'https://www.bloomberg.com/'
			}
		},
		{
			from: 'Jun 2005',
			to: 'Apr 2006',
			title: 'Research Analyst',
			workplace: 'Library House',
			body: [
				'Library House was a buyside data research company focused on providing transparency on private high growth potential companies across Europe. Gathered data on companies by interviewing on average 10 CEOs a week, analyzing company filings and preparing short reports for clients.'
			],
			logo: {
				Icon: LibraryHouse,
				tooltip: 'Library House',
				link: 'https://web.archive.org/web/20060412172903/http://www.libraryhouse.net/www/about/index.php'
			}
		}
	];
</script>

<div id="experience" class="section">
	<div class="my-20 text-xl leading-none text-green-400">&rarr; EXPERIENCE</div>

	<p
		class="mb-12 text-pretty pr-24 text-2xl leading-tight tracking-tight text-white md:text-3xl lg:w-1/2"
	>
		Where I've worked, what I've built, and the impact I've had.
	</p>
	<div
		class="relative
			space-y-12
			pb-4
			sm:pt-8
			sm:before:absolute
			sm:before:inset-0
			sm:before:left-[1px]
			sm:before:h-full
			sm:before:w-[1px]
			sm:before:-translate-x-px
			sm:before:bg-gradient-to-b
			sm:before:from-white/25
			sm:before:via-white/25
			sm:before:to-transparent"
	>
		{#each work as w (w.from + w.to)}
			<Milestone
				from={w.from}
				to={w.to}
				heading={w.title}
				subheading={w.workplace}
				body={w.body}
				keywords={w.keywords}
				skillIcons={w.skillIcons}
				logo={w.logo}
			></Milestone>
		{/each}
	</div>
</div>
