<script>
	import {
		Timeline,
		TimelineItem,
		TimelineSeparator,
		TimelineDot,
		TimelineConnector,
		TimelineContent,
		TimelineOppositeContent
	} from 'svelte-vertical-timeline';

	const positions = [
		{
			dateRange: '2002 - 2005',
			icon: 'https://img.icons8.com/nolan/64/taco.png',
			title: 'University of Cambridge',
			bullets: ['BA (Hons) Computer Science, 2.1 (3.7 GPA equivalent)'],
			onClick: () => {
				console.log('Cambridge clicked');
			}
		},
		{
			dateRange: 'March 2006 - March 2008',
			icon: 'https://img.icons8.com/doodle/48/000000/svetle.png',
			title: 'Bloomberg LP: Software Engineer - Realtime Analytics',
			bullets: [
				'Developed a 24/7 high volume market data alert system using C++ in a distributed UNIX environment'
			],
			onClick: () => {
				console.log('Bloomberg Software Eng clicked');
			}
		},
		{
			dateRange: 'March 2008 - April 2011',
			icon: 'https://img.icons8.com/nolan/64/birthday-cake.png',
			title: 'Bloomberg LP: Engineering Team Leader - Realtime Analytics',
			bullets: [
				'Led a team of 8 engineering and grew usage of market alerts application from 3,000 to 40,000 users'
			],
			onClick: () => {
				console.log('Bloomberg Software Eng Team Leader clicked');
			}
		},
		{
			dateRange: 'April 2011 - Nov 2014',
			icon: 'https://img.icons8.com/nolan/64/birthday-cake.png',
			title: 'Bloomberg LP: Engineering Manager - Market Analytics',
			bullets: [
				'Manager of 4 teams in 3 countries with 22 reports building multiple capital market analysis products'
			],
			onClick: () => {
				console.log('Bloomberg Software Eng Team Leader clicked');
			}
		},
		{
			dateRange: 'Nov 2014 - Nov 2016',
			icon: 'https://img.icons8.com/nolan/64/birthday-cake.png',
			title: 'Bloomberg LP: Engineering Manager - Sales Applications',
			bullets: [
				'Engineering manager for 5 teams (30 reports) in London and New York building a green fields product (DASH), for equity salespeople. Grew to over 3000 daily active users over 18 months.',
				'Secured funding for 10 developers after pitching to BLoomberg LP CEO a new business intelligence platform for equity sales managers based around a personally coded C++ prototype'
			],
			onClick: () => {
				console.log('Bloomberg Software Eng Team Leader clicked');
			}
		},
		{
			dateRange: 'Nov 2016 - Jan 2018',
			icon: 'https://img.icons8.com/nolan/64/birthday-cake.png',
			title: 'Bloomberg LP: New Engineering Initiative - Data Analysis Tools',
			bullets: [
				'Secured seven figure funding after leading the design and build of a functional prototype for a suite of Node.js / React tools for improving the efficiency of data analysts working with stock exchange data.'
			],
			onClick: () => {
				console.log('Bloomberg Software Eng Team Leader clicked');
			}
		},
		{
			dateRange: 'Jan 2018 - May 2019',
			icon: 'https://img.icons8.com/nolan/64/birthday-cake.png',
			title: 'Bloomberg LP: Head Product/Data Engineering - Contributed Data',
			bullets: [
				'With a team of 8 product managers and data engineers grew the business by reducing the time to on-board new content from months to weeks, removed interruptions in data service due to customer firm mergers, and reduced data processing errors from 3% of content to <0.1%',
				'Launched a new Alternative Data business by reducing the on-board time for vendors from weeks to days by developing a new data pipeline system on a Python microservices no-SQL architecture'
			],
			onClick: () => {
				console.log('Bloomberg Software Eng Team Leader clicked');
			}
		},
		{
			dateRange: 'May 2019 - Oct 2020',
			icon: 'https://img.icons8.com/nolan/64/birthday-cake.png',
			title: 'Bloomberg LP: Division Head - Contributed Data',
			bullets: [
				'Lead a 80+ global team of product managers, data engineers and customer success managers ' +
					'growing the marketplace for Bloomberg’s 4000+ data partners. Improving data usage and reducing ' +
					'Bloomberg customer churn, by for example decreasing time partners spend to enable customers from ' +
					'weeks to <5 days, while also improving speed of customer historical data updates from multi-days to ' +
					'<24 hours.'
			],
			onClick: () => {
				console.log('Bloomberg Software Eng Team Leader clicked');
			}
		},
		{
			dateRange: 'Nov 2020 - Dec 2022',
			icon: 'https://img.icons8.com/nolan/64/birthday-cake.png',
			title: 'Meta: Senior Engineering Manager - Facebook Messenger',
			bullets: [
				'Responsible for 3 teams (20 reports) building systems to manage the data generated by Messenger’s 1B+ ' +
					'users. Focus is building a data foundation that is private, with semantic understanding through all ' +
					'processing operations to deliver strong compliance with regulations, with accurate insights, while at ' +
					'massive scale.'
			],
			onClick: () => {
				console.log('Bloomberg Software Eng Team Leader clicked');
			}
		},
		{
			dateRange: 'Oct 2020 - Present',
			icon: 'https://img.icons8.com/nolan/64/birthday-cake.png',
			title: 'Velma: Advisor',
			bullets: [
				'Velma is a VC-backed early stage company using AI to make the process of planning and running large ' +
					'software projects more transparent, efficient and agile. Advise the CEO and executive team on company ' +
					'strategy, fundraising, market positioning and as a general sounding board for hard problems.'
			],
			onClick: () => {
				console.log('Bloomberg Software Eng Team Leader clicked');
			}
		},
		{
			dateRange: 'Jan 2023 - Dec 2023',
			icon: 'https://img.icons8.com/nolan/64/birthday-cake.png',
			title: 'Two Sigma: SVP - Head of Data Platform',
			bullets: [
				"Led a team of Data Engineers responsible for Two Sigma's Data Platform, a suite of tools and services that " +
					"enable Alpha Modelers and other internal customers to discover, share and seamlessly use Two Sigma's vast " +
					'catalog of vendor supplied, proprietary and derived datasets.',
				'Established a process and mechanism to provide comprehensive data lineage tracking across Two Sigma’s ' +
					'operations that enabled use-cases around risk management, support cost reduction and model attribution in a ' +
					'way that did not disrupt modeler workflow or require a rebuild of the existing architecture.',
				'Built a data governance system to provide strong guarantees that all data referenced directly or indirectly by ' +
					'alpha models has appropriate SLAs and access controls.'
			],
			onClick: () => {
				console.log('Bloomberg Software Eng Team Leader clicked');
			}
		},
		{
			dateRange: 'Dec 2023 - Present',
			icon: 'https://img.icons8.com/nolan/64/birthday-cake.png',
			title: 'Two Sigma: SVP - Head of Data Platform & Differentiated Data Engineering',
			bullets: [
				'Leading multiple teams of Data Engineers, Data Scientists and Program Managers responsible for Two ' +
					"Sigma's Data Platform and efforts to build and leverage LLM technology to create differentiated proprietary " +
					'datasets. ',
				'Delivered tools that leverage LLM technology and are used to deliver new sources of alpha, established ' +
					"systems and processes that allow the scalable validation and tuning of LLM's with human input, and created " +
					"new datasets with the team's LLM tools that themselves deliver alpha."
			],
			onClick: () => {
				console.log('Bloomberg Software Eng Team Leader clicked');
			}
		}
	];

	function onClick() {
		console.log('clicked');
	}
</script>

<div class="py-40">
	<Timeline
		position="alternate"
		style={'border: solid 1px #dbdbdb; padding: 50px 0; border-radius: 2%;'}
	>
		{#each positions as position}
			<TimelineItem>
				<TimelineOppositeContent slot="opposite-content">
					<p>{position.dateRange}</p>
				</TimelineOppositeContent>
				<TimelineSeparator>
					<TimelineDot
						style={'width: 45px; height: 45px; background-color: #fff; display: flex; justify-content: center; border-color: transparent; '}
					>
						<button type="button" on:click={position.onClick}>
							<img src={position.icon} alt="" />
						</button>
					</TimelineDot>
					<TimelineConnector />
				</TimelineSeparator>
				<TimelineContent>
					<h3>{position.title}</h3>
					<ul>
						{#each position.bullets as bullet}
							<li>{bullet}</li>
						{/each}
					</ul>
				</TimelineContent>
			</TimelineItem>
		{/each}
	</Timeline>
</div>

<style>
	h3 {
		letter-spacing: 1.5px;
		margin: 0;
		padding: 0;
		color: white;
	}

	li,
	p {
		letter-spacing: 1.5px;
		margin: 0;
		color: grey;
	}
</style>
