<script>
	import { page } from '$app/stores';
	import { browser } from '$app/environment';
	import { onMount, afterUpdate } from 'svelte';
	import { GithubBrands } from 'svelte-awesome-icons';
	import Navbar from '$lib/components/Navbar.svelte';
	import ArticleRenderer from '$lib/components/ArticleRenderer.svelte';
	import mermaid from 'mermaid';

	// Content from your dbt-duckdb.md article
	// For brevity, this is a shortened version. You should include the full markdown content.
	const articleContentString = `
# Modern Data Transformation without a Data Warehouse: A dbt and DuckDB approach

**Link to code:** https://github.com/nickbrett1/dbt-duckdb

## 1. Introduction

Data transformation is a critical step in any data pipeline. For many use cases, cloud data warehouses offer powerful solutions, providing scalability for large datasets and easy access to analytical tools. However, this power often comes with increased complexity, cost, and maintenance overhead. At the other end of the spectrum, simple scripting with file formats like Parquet offers ease of use but can lack the robust structure needed for managing complex transformations as projects evolve.

This article addresses the gap between these two approaches. We present a solution for scenarios where datasets are manageable in size, yet there's a strong need for well-defined, maintainable transformations without incurring the costs and complexities of a full-scale data warehouse. We'll demonstrate how to build such a pipeline locally and deploy with minimal cloud infrastructure by leveraging the combined strengths of dbt-core and DuckDB.

## 3. The Complication: Common Hurdles

*(Content from section 3 would go here...)*

## 5. The Answer: dbt-core Meets DuckDB

### Part 3: The Combined Architecture

Here's a conceptual flow of how they interact:

\`\`\`mermaid
graph TD;
    A["Source Data (e.g., WDI CSV, API extracts)"] --> B["Ingestion Scripts (e.g., Python)"];
    B -- "(writes to)" --> C["Raw Data Storage (e.g., Local Filesystem, Cloud Bucket - Parquet/CSV)"];
    C -- "(raw data feeds into)" --> D["Step 2: DuckDB as Engine (reads raw data, acts as dbt's 'warehouse')"];
    D -- "(dbt-core runs SQL/Python transformations)" --> E["Step 3: DuckDB with Transformed Data (stores intermediate & final results)"];
    E --> F["Step 4: Processed Data Storage (e.g., Local Filesystem, Cloud Bucket - Parquet, Relational DB)"];
    F --> G["(consumed by) Analysis / Visualization / Applications"];
\`\`\`

### Part 4: Showcasing the Results (from the \`dbt-duckdb\` project)

The accompanying GitHub project provides a concrete implementation of this approach using World Development Indicator data. And below are some example visualizations of the transformed data:

- **Embedded Visualizations/Data (Illustrative):**
  - _(Placeholder: Imagine a line graph generated using a Python library like Matplotlib or Seaborn, plotting a key WDI indicator (e.g., GDP per capita) over time for selected countries. This graph would be generated by querying the final transformed data from the DuckDB instance.)_
  - _(Placeholder: Key summary statistics derived from the transformed data, such as the total number of countries processed, the range of years covered, and the count of unique indicators, could be presented here. For example: "Processed data for 217 countries across 50+ indicators from 1960 to 2022.")_

## 6. Appendix: Additional Considerations & Learnings

**A2: Leveraging \`rclone\` for Cloud Storage Agnosticity**
To manage the movement of data to and from cloud storage (like Cloudflare R2 in the example project), \`rclone\` ("rsync for cloud storage") proved to be an invaluable tool.
\`\`\`bash
rclone sync /path/to/local/data remote:bucket/path --checksum
\`\`\`
`;

	onMount(async () => {
		if (browser) {
			mermaid.initialize({
				startOnLoad: false, // We will call run manually
				theme: $page.data.colorScheme === 'dark' ? 'dark' : 'default' // Or 'neutral'
				// securityLevel: 'loose', // Consider if complex diagrams have issues
			});
		}
	});

	afterUpdate(() => {
		if (browser) {
			console.log('Running mermaid diagrams...');
			// Ensure mermaid diagrams are rendered after Svelte has updated the DOM
			// with the content from ArticleRenderer
			mermaid.run({ nodes: document.querySelectorAll('.mermaid') });
		}
	});
</script>

<svelte:head>
	<title>Modern Data Transformation: A dbt and DuckDB Approach</title>
	<meta
		name="description"
		content="Learn how to build efficient data transformation pipelines using dbt-core and DuckDB, avoiding data warehouse complexities."
	/>
</svelte:head>

<Navbar />

<article class="container mx-auto p-4 space-y-8 max-w-6xl">
	<header class="mb-12 mt-8">
		<!-- Breadcrumbs -->
		<div class="text-sm text-gray-400 mb-4">
			<a href="/" class="hover:underline">home</a> /
			<a href="/projects" class="hover:underline">projects</a> /
			<span class="text-white">dbt-duckdb</span>
		</div>

		<!-- Title, Description, and Right-hand Info Block -->
		<div class="flex flex-col md:flex-row md:justify-between md:items-start gap-8">
			<div class="flex-grow">
				<h1 class="text-4xl font-bold text-white !mb-3">
					Modern Data Transformation without a Data Warehouse: A dbt and DuckDB approach
				</h1>
				<p class="text-lg text-gray-400">
					Leveraging dbt-core and DuckDB for efficient, maintainable, and low-cost data pipelines.
				</p>
			</div>
			<!-- Right-hand info section -->
			<div class="flex-shrink-0 md:w-64 space-y-4">
				<!-- View Code Link -->
				<a
					href="https://github.com/nickbrett1/dbt-duckdb"
					target="_blank"
					rel="noopener noreferrer"
					class="flex items-center justify-center w-full bg-gray-700 hover:bg-gray-600 border border-green-800 text-white font-semibold py-2 px-4 rounded transition-colors space-x-2"
				>
					<GithubBrands class="w-5 h-5" />
					<span>Check out the code</span>
				</a>
				<!-- Technology Pills -->
				<div class="flex flex-wrap gap-2 justify-center md:justify-start">
					<span class="bg-gray-600 text-gray-300 text-xs font-medium px-2.5 py-0.5 rounded-full"
						>dbt</span
					>
					<span class="bg-gray-600 text-gray-300 text-xs font-medium px-2.5 py-0.5 rounded-full"
						>DuckDB</span
					>
					<span class="bg-gray-600 text-gray-300 text-xs font-medium px-2.5 py-0.5 rounded-full"
						>Cloudflare</span
					>
				</div>
			</div>
		</div>
	</header>

	<!-- Render the article content -->
	<ArticleRenderer articleMarkdown={articleContentString} />
</article>
