name: Scheduled Preview Environment Cleanup

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: webapp/package-lock.json
      
      - name: Install dependencies
        run: |
          cd webapp
          npm ci
      
      - name: Install Wrangler
        run: |
          cd webapp
          npm install -g wrangler
      
      - name: Setup Wrangler authentication
        run: |
          cd webapp
          echo "${{ secrets.CLOUDFLARE_API_TOKEN }}" | wrangler login
      
      - name: Show cleanup status
        run: |
          cd webapp
          echo "📊 Current preview environment status:"
          ./cleanup-preview-environments.sh status
      
      - name: Run cleanup operations
        run: |
          cd webapp
          echo "🧹 Running scheduled cleanup..."
          ./cleanup-preview-environments.sh cleanup
      
      - name: Show final status
        run: |
          cd webapp
          echo "📊 Final preview environment status:"
          ./cleanup-preview-environments.sh status
      
      - name: Create cleanup summary
        run: |
          echo "## 🧹 Preview Environment Cleanup Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Run Time:** $(date -u)" >> $GITHUB_STEP_SUMMARY
          echo "**Trigger:** ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 📋 What was cleaned up:" >> $GITHUB_STEP_SUMMARY
          echo "- Old preview environments" >> $GITHUB_STEP_SUMMARY
          echo "- Environments for deleted branches" >> $GITHUB_STEP_SUMMARY
          echo "- Orphaned resources" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 💡 Next cleanup:" >> $GITHUB_STEP_SUMMARY
          echo "Scheduled for tomorrow at 2 AM UTC" >> $GITHUB_STEP_SUMMARY